Dao and controller
jcosta86/at28_01 pull request #5
Opened 2021-02-03 17:50 UTC by Delismachado

Category Dao and Controller
Added:
    BaseDao
    BaseController
    CategoryDao
    CategoryController
    Tests

2021-02-03 18:04 UTC, jcosta86 approved these changes

2021-02-03 18:33 UTC, abreumatheus requested changes

2021-02-03 18:33 UTC, abreumatheus commented on src/tests/controllers/test_category_controller.py
> +        assert exc.value == 'Object not found in the database.'
Como visto no dojo, essa linha tem que ficar fora do with da seguinte maneira:
`assert str(exc.value) == 'Object not found in the database.'`

2021-02-03 18:33 UTC, abreumatheus commented on src/tests/dao/test_category_dao.py
> +        category_read = CategoryDao().read_by_id(category_saved.id_)
Seria interessante utilizar uma única instância de CategoryDao

2021-02-03 18:33 UTC, abreumatheus commented on src/tests/dao/test_category_dao.py
> +        category_read = CategoryDao().read_by_id(category_saved.id_)
Seria interessante utilizar uma única instância de CategoryDao

2021-02-04 12:31 UTC, abreumatheus requested changes

2021-02-04 12:31 UTC, abreumatheus commented on requirements.txt
>  psycopg2-binary==2.8.6
Remover psycopg2, visto que não está sendo utilizado.

2021-02-04 12:31 UTC, abreumatheus commented on src/tests/controllers/test_category_controller.py
> +        assert exc.value == 'Object not found.'
Faltou arrumar esse assert da mensagem da exceção.

2021-02-04 12:51 UTC, abreumatheus approved these changes

2021-02-04 12:54 UTC, merged